import { Service, Category } from "../types";

export const CATEGORIES: Category[] = [
  "Birthday",
  "Proposal",
  "Anniversary",
  "Baby shower",
  "Festive",
  "Corporate",
  "Wedding",
  "Gifts",
  "Experience",
];

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Dreamy balloon arch decor",
    description: "A stunning balloon arch with pastel colors and metallic accents, perfect for birthdays and anniversaries.",
    price: 4999,
    originalPrice: 6999,
    rating: 4.8,
    reviews: 124,
    category: "Birthday",
    images: [
      "https://picsum.photos/seed/decor1/800/1200",
      "https://picsum.photos/seed/decor1b/800/1200",
    ],
    inclusions: [
      "200+ balloons",
      "Balloon arch frame",
      "Fairy lights",
      "Setup & cleanup",
    ],
    addons: [
      { id: "a1", name: "Custom name foil", price: 500 },
      { id: "a2", name: "Extra 50 balloons", price: 300 },
    ],
    location: "Mumbai",
    distance: "2.4km",
    tags: ["Decorations", "Balloons"],
    trending: true,
  },
  {
    id: "2",
    title: "Romantic rooftop proposal",
    description: "A private rooftop setup with rose petals, candles, and a 'marry me' neon sign.",
    price: 12999,
    originalPrice: 15999,
    rating: 4.9,
    reviews: 86,
    category: "Proposal",
    images: [
      "https://picsum.photos/seed/proposal1/800/1200",
      "https://picsum.photos/seed/proposal1b/800/1200",
    ],
    inclusions: [
      "Rose petal pathway",
      "100+ scented candles",
      "Neon 'marry me' sign",
      "Private butler service",
    ],
    addons: [
      { id: "a3", name: "Professional photographer", price: 3000 },
      { id: "a4", name: "Violinist for 30 mins", price: 5000 },
    ],
    location: "Delhi",
    distance: "5.1km",
    tags: ["Romantic", "Rooftop"],
    trending: true,
  },
  {
    id: "3",
    title: "Golden anniversary gala",
    description: "Elegant gold and white theme with floral arrangements and premium backdrop.",
    price: 8999,
    originalPrice: 10999,
    rating: 4.7,
    reviews: 52,
    category: "Anniversary",
    images: [
      "https://picsum.photos/seed/anniv1/800/1200",
    ],
    inclusions: [
      "Gold backdrop",
      "Fresh flower bouquets",
      "Number foils (50)",
      "Cake table decor",
    ],
    addons: [
      { id: "a5", name: "Champagne bottle", price: 2500 },
    ],
    location: "Bangalore",
    distance: "3.5km",
    tags: ["Anniversary", "Premium"],
    trending: false,
  },
  {
    id: "4",
    title: "Boho baby shower setup",
    description: "Bohemian style decor with macrame, pampas grass, and soft lighting.",
    price: 6499,
    originalPrice: 7999,
    rating: 4.6,
    reviews: 38,
    category: "Baby shower",
    images: [
      "https://picsum.photos/seed/baby1/800/1200",
    ],
    inclusions: [
      "Macrame backdrop",
      "Pampas grass decor",
      "Soft cushions & rugs",
      "Welcome board",
    ],
    addons: [
      { id: "a6", name: "Baby name blocks", price: 800 },
    ],
    location: "Pune",
    distance: "1.8km",
    tags: ["Baby Shower", "Boho"],
    trending: true,
  },
  {
    id: "5",
    title: "Neon party vibes",
    description: "High-energy neon decor with UV lights and glow-in-the-dark elements.",
    price: 5499,
    originalPrice: 6499,
    rating: 4.5,
    reviews: 92,
    category: "Birthday",
    images: [
      "https://picsum.photos/seed/neon1/800/1200",
    ],
    inclusions: [
      "UV flood lights",
      "Neon balloons",
      "Glow sticks (50)",
      "Blacklight backdrop",
    ],
    addons: [
      { id: "a7", name: "Smoke machine", price: 1500 },
    ],
    location: "Mumbai",
    distance: "4.2km",
    tags: ["Party", "Neon"],
    trending: false,
  },
  {
    id: "6",
    title: "Enchanted Forest Theme",
    description: "Whimsical forest decor with artificial trees, moss, and fairy lights.",
    price: 7499,
    originalPrice: 8999,
    rating: 4.8,
    reviews: 45,
    category: "Birthday",
    images: ["https://picsum.photos/seed/forest/800/1200"],
    inclusions: ["Artificial Trees", "Moss Runners", "Fairy Lights", "Animal Cutouts"],
    addons: [{ id: "a8", name: "Fog Machine", price: 1200 }],
    location: "Bangalore",
    distance: "6.0km",
    tags: ["Theme", "Forest"],
    trending: true,
  },
  {
    id: "7",
    title: "Vintage Cinema Night",
    description: "Retro movie night setup with popcorn machine and vintage posters.",
    price: 4500,
    originalPrice: 5500,
    rating: 4.7,
    reviews: 29,
    category: "Experience",
    images: ["https://picsum.photos/seed/cinema/800/1200"],
    inclusions: ["Projector Screen", "Popcorn Machine", "Vintage Posters", "Bean Bags"],
    addons: [{ id: "a9", name: "Extra Popcorn", price: 300 }],
    location: "Mumbai",
    distance: "2.1km",
    tags: ["Experience", "Cinema"],
    trending: true,
  },
  {
    id: "8",
    title: "Under the Sea Adventure",
    description: "Blue and teal balloon decor with sea creature foils.",
    price: 3999,
    originalPrice: 4999,
    rating: 4.5,
    reviews: 67,
    category: "Birthday",
    images: ["https://picsum.photos/seed/sea/800/1200"],
    inclusions: ["Sea Creature Foils", "Blue Balloon Arch", "Bubble Machine", "Sand Pit"],
    addons: [{ id: "a10", name: "Mermaid Performer", price: 4000 }],
    location: "Delhi",
    distance: "3.8km",
    tags: ["Theme", "Sea"],
    trending: true,
  }
];
